services:
  web:
    build: .
    ports:
      - "5100:5000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SESSION_TIMEOUT_MINUTES=120
      - SESSION_MESSAGE_LIMIT=15
    depends_on: Om a
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9100:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  elasticsearch-data: 